# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import route_guide_pb2 as route__guide__pb2


class RouteGuideStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRedditPost = channel.unary_stream(
                '/app.RouteGuide/SendRedditPost',
                request_serializer=route__guide__pb2.PostRequestReddit.SerializeToString,
                response_deserializer=route__guide__pb2.GetRedditPost.FromString,
                )
        self.SendYouTubePost = channel.unary_stream(
                '/app.RouteGuide/SendYouTubePost',
                request_serializer=route__guide__pb2.PostRequestYoutube.SerializeToString,
                response_deserializer=route__guide__pb2.GetYouTubePost.FromString,
                )


class RouteGuideServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendRedditPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendYouTubePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendRedditPost': grpc.unary_stream_rpc_method_handler(
                    servicer.SendRedditPost,
                    request_deserializer=route__guide__pb2.PostRequestReddit.FromString,
                    response_serializer=route__guide__pb2.GetRedditPost.SerializeToString,
            ),
            'SendYouTubePost': grpc.unary_stream_rpc_method_handler(
                    servicer.SendYouTubePost,
                    request_deserializer=route__guide__pb2.PostRequestYoutube.FromString,
                    response_serializer=route__guide__pb2.GetYouTubePost.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.RouteGuide', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RouteGuide(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendRedditPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/app.RouteGuide/SendRedditPost',
            route__guide__pb2.PostRequestReddit.SerializeToString,
            route__guide__pb2.GetRedditPost.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendYouTubePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/app.RouteGuide/SendYouTubePost',
            route__guide__pb2.PostRequestYoutube.SerializeToString,
            route__guide__pb2.GetYouTubePost.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
